# Generated by Django 5.1.1 on 2024-09-05 13:49

import database.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(max_length=128, unique=True)),
                ("nfc_id", models.BinaryField(max_length=7, unique=True)),
                (
                    "discord",
                    models.CharField(
                        max_length=32,
                        null=True,
                        unique=True,
                        validators=[database.validators.discord_username_validator],
                    ),
                ),
                ("is_crew", models.BooleanField(default=False)),
            ],
        ),
    ]
