# Generated by Django 5.0.3 on 2024-09-19 13:12

import database.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendant",
            name="discord",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
                validators=[database.validators.discord_username_validator],
            ),
        ),
        migrations.AlterField(
            model_name="attendant",
            name="ticket_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
