# Generated by Django 5.0.3 on 2024-09-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_alter_attendant_discord_alter_attendant_ticket_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendant",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
