# Generated by Django 5.1.3 on 2025-01-06 22:56

import database.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_attendant_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='discord',
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('discord', models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[database.validators.discord_username_validator])),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.attendant')),
            ],
        ),
    ]
