# Generated by Django 5.1.5 on 2025-02-27 15:12

import database.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_remove_attendant_discord_crew"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crewmember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=200)),
                (
                    "discord",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        validators=[database.validators.discord_username_validator],
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name="attendant",
            name="nfc_id",
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name="attendant",
            name="crewinfo",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="database.crewmember",
            ),
        ),
        migrations.AddField(
            model_name="crewmember",
            name="crew",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.crews",
            ),
        ),
        migrations.DeleteModel(
            name="Crew",
        ),
    ]
