name: "Run tests"
on:
  push:

jobs:
  test:
    if: ${{ github.repository_owner == 'EventAccess' }}

    strategy:
      fail-fast: false
      matrix:
        py_version: ['3.12']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Git checkout
        uses: "actions/checkout@v4.2.1"

      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.py_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Run tests
        run: bash ./.github/workflows/run-tests.sh


